# Generated by Django 5.2.1 on 2025-05-30 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TableB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ecarts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecart', models.FloatField()),
                ('table_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spark.tablea')),
                ('table_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spark.tableb')),
            ],
        ),
    ]
