# Generated by Django 5.2.1 on 2025-06-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('valeur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DatasetB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('valeur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ecart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('ecart_valeur', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Identique', 'Identique'), ('Différent', 'Différent'), ('Nouveau', 'Nouveau')], max_length=10)),
                ('methode', models.CharField(choices=[('Spark', 'Spark'), ('Django', 'Django')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='ecarts',
            name='table_a',
        ),
        migrations.RemoveField(
            model_name='ecarts',
            name='table_b',
        ),
        migrations.DeleteModel(
            name='TableA',
        ),
        migrations.DeleteModel(
            name='Ecarts',
        ),
        migrations.DeleteModel(
            name='TableB',
        ),
    ]
